### ISSUE TITLE
oci_connect(): ORA-12170: TNS:Connect timeout occurred

### ISSUE THREAD

**Issue by dikkykurnia** [yajra/laravel-oci8#111]
I'm install oracle client on my homestead, and success connect to oracle,but when i connect using my laravel application with yajra on it, it got TNS:Connect timeout occurred. my oracle server is on different computer separate with my homestead.

**Comment by yajra** [comment]
Where you able to properly configure `oci8` extension? Try using this script to fix the installation of oci8.
https://github.com/yajra/homestead-oracle/blob/master/scripts/install-oci8.sh

**Comment by dikkykurnia** [comment]
yes oci8 extension is already set in both /etc/php5/fpm/php.ini and /etc/php5/cli/php.ini, and its detected by php, i can connect to oracle server using sqlplus

**Comment by yajra** [comment]
Does ORACLE home LD path properly set? And were you able to connect using the native way using `oci_connect`?

```sh
	echo "env[ORACLE_HOME] = '/u01/app/oracle/product/11.2.0/xe'" >> /etc/php5/fpm/php-fpm.conf
	echo "env[LD_LIBRARY_PATH] = '/u01/app/oracle/product/11.2.0/xe/lib'" >> /etc/php5/fpm/php-fpm.conf
```

**Comment by dikkykurnia** [comment]
my oracle server is in another computer not in my homestead so idon't set oracle home ld,using oci_connect connect perfectly

**Comment by yajra** [comment]
Hmm. Can you try using the TNS you used on native way and set it as the TNS for the package? You can do this by setting the config `'tns' => 'tns_string'`.

On the other hand, ORA-12170 seems like an issue where homestead cannot reach the Oracle server. Can you double check the SID you're using. I think it's case sensitive.

**Comment by dikkykurnia** [comment]
in Oci8.php line 84
at HandleExceptions->handleError('2', 'oci_connect(): ORA-12170: TNS:Connect timeout occurred', '/home/vagrant/Code/restApiRSHS/vendor/yajra/laravel-pdo-via-oci8/src/yajra/Pdo/Oci8.php', '84', array('dsn' => 'orcl', 'username' => 'homestead', 'password' => 'secret', 'options' => array('2', '2', '0', 'charset' => 'AL32UTF8'), 'charset' => 'AL32UTF8'))
at oci_connect('homestead', 'secret', 'orcl', 'AL32UTF8') in Oci8.php line 84
at Oci8->__construct('orcl', 'homestead', 'secret', array('2', '2', '0', 'charset' => 'AL32UTF8')) in OracleConnector.php line 189
at OracleConnector->createConnection('orcl', array('driver' => 'oracle', 'tns' => 'orcl', 'host' => 'localhost', 'port' => '1521', 'database' => 'homestead', 'username' => 'homestead', 'password' => 'secret', 'charset' => 'AL32UTF8', 'prefix' => ''), array('2', '2', '0')) in OracleConnector.php line 36
at OracleConnector->connect(array('driver' => 'oracle', 'tns' => 'orcl', 'host' => 'localhost', 'port' => '1521', 'database' => 'homestead', 'username' => 'homestead', 'password' => 'secret', 'charset' => 'AL32UTF8', 'prefix' => '')) in Oci8ServiceProvider.php line 40
at Oci8ServiceProvider->yajra\Oci8\{closure}(array('driver' => 'oracle', 'tns' => 'orcl', 'host' => 'localhost', 'port' => '1521', 'database' => 'homestead', 'username' => 'homestead', 'password' => 'secret', 'charset' => 'AL32UTF8', 'prefix' => ''), 'oracle')

my host isn't localhost,my username isn't homestead,my password isn't secret

**Comment by ChaosPower** [comment]
@dikkykurnia I can't replicate your issue. Can you  do ```cat /etc/environment``` and paste it here?
If you installed your instantclient correctly you should have similar environment with mine.

```
LD_LIBRARY_PATH="/usr/local/lib/instantclient_11_2"
TNS_ADMIN="/usr/local/lib/instantclient_11_2"
ORACLE_BASE="/usr/local/lib/instantclient_11_2"
ORACLE_HOME=$ORACLE_BASE

OCI_LIB_DIR="/usr/local/lib/instantclient_11_2"
OCI_INCLUDE_DIR="/usr/local/lib/instantclient_11_2/sdk/include"
OCI_VERSION=11
```

This is the guide I used for installing instantclient https://help.ubuntu.com/community/PHPOracle

is port 1521 allowed in your firewall? ```ufw allow 1521```

Are you using .env file? Please check your configuration.

**Comment by dikkykurnia** [comment]
solved already,thanks

**Comment by yajra** [comment]
@dikkykurnia, Is it ok for you to share how you solved this issue? To be used as reference for future users that might encounter the same error. ^_^ Thanks!

**Comment by dikkykurnia** [comment]
i was set oracle.php like this :
driver'   => 'oracle',
            'tns'      => env('DB_TNS', 'orcl'),
            'host'     => env('DB_HOST', 'my server ip'),
            'port'     => env('DB_PORT', '1521'),
            'database' => env('DB_DATABASE', ''),
            'username' => env('DB_USERNAME', 'username'),
            'password' => env('DB_PASSWORD', 'pwd'),
            'charset'  => 'AL32UTF8',
            'prefix'   => '',
but it's not working till i change like this : 

'driver'   => 'oracle',
            //'tns'      => 'orcl',
            'tns'      => '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=myserver ip)(PORT=1521)) (CONNECT_DATA=(SERVICE_NAME=orcl)))',
            //'host'     => 'myserver ip',
            //'port'     => '1521',
            'database' => '',
            'username' => 'username',
            'password' => 'pwd',
            'charset'  => 'AL32UTF8',
            'prefix'   => '',

**Comment by yajra** [comment]
I see, you're Oracle installation uses service name instead of SID. You can try defining service name on your config if you don't like the long TNS string. https://github.com/yajra/laravel-oci8/wiki/Installation

```php
'driver' => 'oracle',
'service_name' => 'orcl',
'database' => '',
'username' => 'username',
'password' => 'pwd',
'charset' => 'AL32UTF8',
'prefix' => '',
```
Thanks for sharing your solution.

**Comment by CJEdgerton** [comment]
Hi all,

I'm having issues with this as well and still having trouble after reading over this tread.

Details:
- The good - works on dev setup
   - Using `valet` on my dev machine, I am able to connect and everything works fine.
   - Using wireshark I can see the requests going from my machine to the oracle server, and vice versa when my app is querying the db.
- The bad - doesn't work on production server (age old problem)
   - On my production machine running IIS7 I'm receiving `'ORA-12170: TNS:Connect timeout occurred'`.
   - I'm using the exact same config files as dev (`/config/oracle.php` and `.env` added below)
   - Using Wireshark, I cannot see any traffic going to the oracle server when running migrations or loading application pages that I know query the oracle db. Which is weird since the error states that it is timing out.

I don't have access to the oracle server, and the dba/contact in my organization doesn't seem very technical. Initially they told me to connect with SQL Developer, Oracle's gui client to get the data I needed. The connection info the gave me which works in SQL Developer is below:

## Connection info given to me by dba
```
Username: MY_USER_NAME
Password: MY_PASSWORD
Host: my.oracle.host.com
Port: 1521
SID: SQNADC
Schema: MY_DATACACHE
```
** Note: I am using the 'basic' connection type in SQL Developer, which didn't require the use of  the `Schema` - `MY_DATACACHE` string anywhere so far. **

## /config/oracle.php
```php
    'oracle' => [
        'driver'       => 'oracle',
        'host'         => env('DB_ORACLE_HOST', ''),
        'port'         => env('DB_ORACLE_PORT', '1521'),
        'database'     => env('DB_ORACLE_DATABASE', ''),
        'service_name' => env('DB_ORACLE_SID_ALIAS', ''),
        'username'     => env('DB_ORACLE_USERNAME', ''),
        'password'     => env('DB_ORACLE_PASSWORD', ''),
        'charset'      => '',
        'prefix'       => '',
    ],
```

## .env
```
DB_CONNECTION=sqlite

DB_ORACLE_HOST=my.oracle.host.com
DB_ORACLE_PORT=1521
DB_ORACLE_DATABASE=SQNADC
DB_ORACLE_USERNAME=MY_USER_NAME
DB_ORACLE_PASSWORD=MY_PASSWORD
```

## Production (IIS7) Server settings
- Enabled extensions:
```
...
php_oci8_12c.dll
php_pdo_oci.dll
...
```
- Firewall is allowing all outgoing traffic

** Note: 
- If I add `'tns' => 'MY_DATACACHE',` (`Schema` - `MY_DATACACHE` from dba's connection info) into the `oracle` array in `/config/oracle`,  when connecting:
   - I can see requests go out in WireShark of protocol LLMNR and NBMS protocol, that mention `Name query MY_DATACACHE<00>` in the information column, the destination IP isn't however the oracle server but an unknown IP, from a little reading it seems that this is probably ignorable though?

Maybe TMI but thought I'd be thorough. Any help appreciated.
Thanks
