### ISSUE TITLE
Keys naming convention

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [yajra/laravel-oci8#131]
Hello!

As we know, Oracle have a length limit of 30 for some objects, like primary keys, foreign keys, unique keys.

When creating a table with multiple names, like `request_queue_dispatch`, which may reference another table, will force us to manually set the primary and foreign key names, because it will for sure overflow that 30 char limit.

Usually, renaming from "primary" to "pk", or "foreign" to "fk" solves this issue.

So, my suggestion is to change the naming convention for this kind of objects, like:

'primary' to 'pk'
'foreign' to 'fk'
'unique' to 'uk'

This way, the sample said above, which will have a overflowed object like 'request_queue_dispatch_id_primary', will be created as 'request_queue_dispatch_id_pk', which does not overflow the 30 char limit.

Just a suggestion, to avoid lots of pk and fk renaming on migration scripts.

**Comment by yajra** [comment]
I agree with this suggestion. The naming convention was still the original implementation from JFelder's version which follows the standard naming convention in Laravel. However, due to the fact of Oracle's 30char limitation I guess we should try and compress it to minimum. 

Open for PR if you can work it out but will also try to implement this on my free time. Thanks!

**Comment by rafael-renan-pacheco** [comment]
Cool, just coded it here, will PR as soon I can.

Best regards

**Comment by yajra** [comment]
PR released on v4.2.0. Thanks!
