### ISSUE TITLE
compatibility issue with Illuminate\Database\Query\Builder

### ISSUE THREAD

**Issue by AviRns** [yajra/laravel-oci8#152]
i am getting the following error while executing the code below.
*Declaration of yajra\Oci8\Query\OracleBuilder::pluck() should be compatible with Illuminate\Database\Query\Builder::pluck($column, $key = NULL)*

```use Illuminate\Database\Capsule\Manager as DB;```

```$users = DB::table('users')->where('ticket_no', '499313')->first();
var_dump($users);```

Please help.

**Comment by yajra** [comment]
@AviRns, what version of Laravel are you using? I think this is 5.2 and I suggest you update to version `^4.0`. As far I remember, I already did a similar fix for this same issue for 5.2 compatibility.

**Comment by AviRns** [comment]
I am using Illuminate ~5.0 with slim.

**Comment by yajra** [comment]
@AviRns, may I know your specific version of laravel-oci8 package? Thanks!

**Comment by yajra** [comment]
BTW, using ~5.0 of illuminate will install 5.2 and if you are using ~2.0 of the package then it might indeed go wrong. I just realized a week or so ago that I should have released a version specific for each Laravel version. My version 4.0 and below tried to support most of the version which in turn was not able to manage the conflicts on each new releases of Laravel.

It is possible for you to update and use v5.2.* of package instead? A breaking change though was added on 5.2 due to oracle reserved words.

If possible, can you please submit a PR? Thanks!

**Comment by AviRns** [comment]
@yajra Thank you for your kind help,
sorry for delayed reply as i was out of station.

My composer.json file look like this --
```
"require": {
        "slim/slim": "~2.6",
        "slim/views": "0.1.*",
        "twig/twig": "~1.5",
        "phpmailer/phpmailer": "~5.2",
        "hassankhan/config": "0.8.*",
        "illuminate/database": "5.2",
        "alexgarrett/violin": "2.*",
        "ircmaxell/random-lib": "~1.1",
        "yajra/laravel-oci8": "~2.0",
        "nesbot/carbon": "^1.21"
    }
```

Please let me know what changes may i do to work the above code.

**Comment by yajra** [comment]
@AviRns, sorry for the delayed response. You would need to update the package and use `"yajra/laravel-oci8": "5.2.*",`. Afterwards, you would need to update the namespace from `yajra\Oci8` to `Yajra\Oci8`. 

Please note that when using v5.2, oracle reserved words are now enclosed with double quotes like `"sequence"`. If your column name uses a reserved word, then 5.2 may break your app.

**Comment by AviRns** [comment]
Thank you so much Arjay..
It is working.

i will get back to you whenever i get into problems.

Regards
Avinash
