### ISSUE TITLE
Reserver words should be transform  to Uppercase-converted letter in an insert SQL

### ISSUE THREAD

**Issue by Exia081** [yajra/laravel-oci8#157]
When I use laravel own register functionality ,
I got an error like that 

`Error Message : ORA-00904: "password": invalid identifier
Position : 50
Statement : insert into users (name, display_name, email, "password", updated_at, created_at) values (:p0, :p1, :p2, :p3, :p4, :p5) returning id into :p6`

I add code in 
vendor/yajra/laravel-oci8/src/Oci8/Query/Grammars/OracleGrammar.php
under line 183 
`$columns = strtoupper($columns);`

problem solved 

Is it a good way to solve this problems ?

                                                please forgive my poor English ...

**Comment by yajra** [comment]
Setting it to uppercase will break current installation because the package uses lower case columns.

Are your tables migrated via Laravel or already exists? Or are you upgrading from lower version of the package?

What I am thinking atm is to make oracle reserved words optional via config file. Will dig this further when I had the chance. Thanks!

**Comment by Exia081** [comment]
You remind me something .
When I ran the command `composer update` upgrading laravel 5.1 to 5.2 and oci8 ~2.0 to  5.2.*,I forgot submit it to svn and run svn update ,so the old lirbary download to local again ! 
Now I reinstall laravel 5.2 and oci8 ,this problems disappear .
I think this problem caused by my mistake.

                                                                I’m sorry to bother you.
