### ISSUE TITLE
Very Rare ora-24415 missing or null username on refresh

### ISSUE THREAD

**Issue by andrei0x309** [yajra/laravel-oci8#174]
I don't know if this is an issue or if it had been fixed,I am currently using version v4.2.6 laravel-oci8 on Laravel 5.2, and I had the connection settings only in the oracle.php config file, and I was getting the error ora-24415 on very, very rare occasions 1 out of 20-30 requests. 
So I guessed it may be an error caused by a bug when config values are retrieved, and so i copied the oracle array from oracle.php to the database.php config file and the issue has gone away. 

Contents of my oracle.php file:

```
return [
'oracle' => [
    'driver'   => 'oracle',
    'tns'      => env('DB_TNS', ''),
    'host'     => env('DB_HOST', 'localhost'),
    'port'     => env('DB_PORT', '1521'),
    'database' => env('DB_DATABASE', ''),
    'username' => env('DB_USERNAME', ''),
    'password' => env('DB_PASSWORD', ''),
    'charset'  => env('DB_CHARSET', 'AL32UTF8'),
    'prefix'   => env('DB_PREFIX', ''),
],
];
```

**Comment by yajra** [comment]
@azrael-sub7, I haven't encountered this issue on any of my oracle projects yet. Anyways, thanks for the hint that adding the config to `datatabase.php` to fix the issue. Will try to look further on this issue when I had the chance.

**Comment by bk110w** [comment]
I am also facing this issue while using this library with Lumen (v5.2). All of my DB connection parameters are listed in the high level .env file in the root of the Lumen build. I am using v5.2.4 of this library  (this project has been a huge help to me - thank you very much). I'll update here if I find a suitable workaround for Lumen.

**Comment by jwilliamsnephos** [comment]
I'll be a third person to say I've encountered the issue.  In about a 5 minute stress test scenario with about 15 users hitting my system, it happened over 20 times.

I haven't found a solution for it yet, and the hint about having your settings retrieved in database.php vs an external, we were already setting the connections directly in the database.php.

We didn't see this during development, only during a light stress test.  I'm digging into it, but don't have anything to offer as to a root cause or solution yet.




Stack:
______________________________
[2016-09-20 13:40:15] production.ERROR: Yajra\Pdo\Oci8\Exceptions\Oci8Exception: ORA-24415: Missing or null username. in /devserver/opt/portal/vendor/yajra/laravel-pdo-via-oci8/src/Pdo/Oci8.php:466
Stack trace:
#0 /devserver/opt/portal/vendor/yajra/laravel-pdo-via-oci8/src/Pdo/Oci8.php(78): Yajra\Pdo\Oci8->connect('(DESCRIPTION = ...', '', '', Array, 'AL32UTF8')
#1 /devserver/opt/portal/vendor/yajra/laravel-oci8/src/Oci8/Connectors/OracleConnector.php(189): Yajra\Pdo\Oci8->__construct('(DESCRIPTION = ...', '', '', Array)
#2 /devserver/opt/portal/vendor/yajra/laravel-oci8/src/Oci8/Connectors/OracleConnector.php(36): Yajra\Oci8\Connectors\OracleConnector->createConnection('(DESCRIPTION = ...', Array, Array)
#3 /devserver/opt/portal/vendor/yajra/laravel-oci8/src/Oci8/Oci8ServiceProvider.php(42): Yajra\Oci8\Connectors\OracleConnector->connect(Array)
#4 [internal function]: Yajra\Oci8\Oci8ServiceProvider->Yajra\Oci8\{closure}(Array, 'app')
#5 /devserver/opt/portal/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(173): call_user_func(Object(Closure), Array, 'app')
#6 /devserver/opt/portal/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(68): Illuminate\Database\DatabaseManager->makeConnection('app')
#7 /devserver/opt/portal/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(317): Illuminate\Database\DatabaseManager->connection()
#8 /devserver/opt/portal/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): Illuminate\Database\DatabaseManager->__call('listen', Array)
#9 /devserver/opt/portal/app/Providers/AppServiceProvider.php(20): Illuminate\Support\Facades\Facade::__callStatic('listen', Array)
#10 [internal function]: App\Providers\AppServiceProvider->boot()
#11 /devserver/opt/portal/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#12 /devserver/opt/portal/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\Container\Container->call(Array)
#13 /devserver/opt/portal/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(740): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\AppServiceProvider))
#14 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\AppServiceProvider), 11)
#15 /devserver/opt/portal/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(741): array_walk(Array, Object(Closure))
#16 /devserver/opt/portal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#17 /devserver/opt/portal/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#18 /devserver/opt/portal/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(232): Illuminate\Foundation\Application->bootstrapWith(Array)
#19 /devserver/opt/portal/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(127): Illuminate\Foundation\Http\Kernel->bootstrap()
#20 /devserver/opt/portal/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#21 /devserver/opt/portal/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#22 {main}

**Comment by jwilliamsnephos** [comment]
Made it use persistent connections.  We'll see if this makes a difference at the next stress test.

            'options'       => [
                                PDO::ATTR_PERSISTENT => true
                               ],

**Comment by yajra** [comment]
Reading some issues on framework, I bumped onto something that I think is similar to this. And as per this issue https://github.com/laravel/framework/issues/8191#issuecomment-253115120, doing `php artisan config:cache` might solve the issue. Can anyone confirm this? Thanks!

**Comment by milon** [comment]
I am facing the same issue. And the sad part is, `php artisan config:cache` can't fix the issue. In my development environment(Mac OS sierra, php 7.0.12, laravel 5.3) if works fine, but in my production server(Ubuntu 14.04.4, php 7.0.11, laravel 5.3) it is not working. Any solution?

**Comment by chrislandeza** [comment]
Facing the same issue.
doing `php artisan config:cache` solved it for me.

**Comment by jwilliamsnephos** [comment]
Sorry, I 'm just responding back.  The config:cache did seem to solve the problem for us.

**Comment by P4Thi0ut** [comment]
The config:cache isn't available for Lumen, so if anyone has any hint to solve this I'll be grateful :)

**Comment by anugrahdputra** [comment]
> Facing the same issue.
> doing `php artisan config:cache` solved it for me.

this works for me

**Comment by waleedazam** [comment]
Facing the same issue.
on Laravel 8.x
problem accrued because of  `->change()` in the migration file
