### ISSUE TITLE
Sequence of model

### ISSUE THREAD

**Issue by tratotui** [yajra/laravel-oci8#189]
OracleEloquent has nice method **getSequenceName**, but i didn't find where it used. 
Maybe the best place would be to use it in this context?
Now:

``` php
// file Oci8/Query/Processors/OracleProcessor.php#L62
if ($model->sequence && $model->incrementing) {
    $values[] = (int) $model->getConnection()->getSequence()->nextValue($model->sequence);
}
```

Future:

``` php
if ($model->sequence && $model->incrementing) {
    $values[] = (int) $model->getConnection()->getSequence()->nextValue($model->getSequenceName());
}
```

**Comment by yajra** [comment]
@tratotui, **getSequenceName** method was added back then when I was tinkering how I can get the sequence value but was never completed.

On your proposed **future**, I guess it's possible with some checks because **getSequenceName** is not available on the base eloquent model.

I think something like this might work:
```php
if ($model->sequence && $model->incrementing) {
    $sequence = method_exists($model, 'getSequenceName')
        ? $model->getSequenceName()
        : $model->sequence;
    $values[] = (int) $model->getConnection()->getSequence()->nextValue($sequence);
}
```

**Comment by yajra** [comment]
Added a new method on master (Laravel 5.5) for this. Thanks!

```php
public static function nextValue();
```

## Example
```php
class Fax extends Model {
  public $incrementing = false;
  public $sequence = 'fax_seq';
}

$fax = new Fax;
$fax->faxid = Fax::nextValue();
$fax->save();
```
