### ISSUE TITLE
Database Connect Becomes Stale in Long Running Queue Processes

### ISSUE THREAD

**Issue by timnolte** [yajra/laravel-oci8#191]
Using Laravel 5.1 I've got jobs running under Supervisord and the Oracle connections go stale and start failing causing all jobs to end up failing. Seems there needs to be a more automated process to refresh the connections. See the Laravel issue (https://github.com/laravel/framework/issues/5311) for reference details. Seems they fixed this for MySQL/MariaDB connections as we don't have any problems with the MySQL/MariaDB queries happening in the same jobs.

**Comment by yajra** [comment]
@timnolte do you have any ref on which commit the fix was done? Or this maybe related to the queuing part of Laravel that I think is part of L5.3 updates? I think I've read somewhere that queuing was improved.

Anyways, will try to check if I can replicate the issue. But if you can, please submit a PR for a fix. Thanks!
