### ISSUE TITLE
stored procedure return a cursor

### ISSUE THREAD

**Issue by wipflash** [yajra/laravel-oci8#197]
I  have issue with following statement. There is a variable `$lista` how I defined this variable. 
`$stmt->bindParam(':pTabResultado', $lista, PDO::PARAM_STMT);`

I have used [TiagoGoddard](https://github.com/yajra/laravel-oci8/issues/31) example

**Comment by yajra** [comment]
Can you please paste the error dump?

**Comment by yajra** [comment]
@wipflash what version are you using? Anyways, check this PR https://github.com/yajra/laravel-oci8/pull/200/files to get a snippet on we implement a procedure returning a cursor. 

It's available for 5.3 but should be doable on version 5.2 and below using the same approach.

**Comment by TiagoGoddard** [comment]
I know it's old, just so we close this issue:

`$lista` is a local variable that didn't exist before the `$stmt->bindParam(':pTabResultado', $lista, PDO::PARAM_STMT);`.

Since the parameter is bound to an OUT result on my procedure, it's created at the moment you bind the parameter to that variable.
It will only receive a value when you execute `oci_execute($lista, OCI_DEFAULT);`

You could declare it if you want, but I didn't since it's used only in the local scope of the transaction.

**Comment by mstaack** [comment]
@TiagoGoddard  i have refactored the procedure calls. please check Oci8Connection Methods.

Cheers Max
