### ISSUE TITLE
Booleans saved as chars rather than int

### ISSUE THREAD

**Issue by AdamWillden** [yajra/laravel-oci8#20]
Hi,

I'm curious as to whether there was a reason that [booleans were stored as chars rather than ints.](https://github.com/yajra/laravel-oci8/blob/master/src/yajra/Oci8/Schema/Grammars/OracleGrammar.php#L535)

The issue this causes is that any JSON returned from the server is then a string of "0" and "1" which are both truthy values in JavaScript meaning we always have to parseInt(data.paramName) to get an appropriate boolean value.

[It seems the intention here is to use ints for booleans (?)](https://github.com/yajra/laravel-pdo-via-oci8/blob/master/src/yajra/Pdo/Oci8/Statement.php#L225) or is that just to convert the char value to "0" & "1"?

If there's no reason for them being set as chars rather than ints then I propose this is changed. As it is part of the blueprint/creation of a table this _shouldn't_ be a breaking change and I assume would mean new tables use ints.

**Comment by FrancescoGd** [comment]
Sorry for grave-digging this :D but I've just stumbled upon this problem myself... I believe the decision behind the boolean -> char mapping was due to Oracle's own AskTom suggestion about using it for boolean Y/N and not because of memory footprint. 
Anyway, since the original answer, they changed their stance and suggested to use number fields instead. Localization issues are among the reasons given.
[Here's the original discussion and relevant comment](https://asktom.oracle.com/pls/asktom/asktom.search?tag=boolean-datatype#876972400346931526)
