### ISSUE TITLE
Return Native Type in Query Results

### ISSUE THREAD

**Issue by thachp** [yajra/laravel-oci8#233]
### Summary of problem or feature request

I have multiple columns in a table defined as "NUMBER"  data type in Oracle.  I would like my query results to return type "INT" in PHP.  How should I go about it?  The primary key of ID always cast INT;  I would like similar behavior to apply to other NUMBER field types in the same table.

I tried attribute casting by adding the field name in the $casts model properties... but it isn't what I'm looking because it would require me to define all the field types for all tables that I support, which is a lot.

I could loop all my results and cast each fields, but it would impact the application performance. 

https://laravel.com/docs/5.3/eloquent-mutators#attribute-casting

### Code snippet of problem

```php
$results = \DB::table('example')->all();
var_dump($results);
```

### System details

- Operating System: Linux
- PHP Version 6
- Laravel Version 5.3
- Laravel-OCI8 Version 5.3

**Comment by yajra** [comment]
I think doing this would also affect our application performance since we might need to first fetch all the table column definitions/meta to properly cast each fields to it's proper data type.

On the other hand, if you have some idea on how we can achieve this without affecting the performance. I would gladly accept a PR. Thanks!
