### ISSUE TITLE
yajra/laravel-oci8 v5.6.1 requires ext-oci8 >=2.0.0 - > the requested PHP extension oci8 is missing from your system

### ISSUE THREAD

**Issue by raylucker** [yajra/laravel-oci8#429]
### Summary of problem or feature request

I tried to run composer require yajra/laravel-oci8:"5.6.*" OR composer require yajra/laravel-oci8, it resulted the error on the title.
I tried to use every oci8 dll available for PHP 7.2 (x86 TS, x86 NTS, x64 TS, x64 NTS) but still the laravel oci cant be installed. I previously used the 7.1 php but have to updated it to the latest version for maybe it gives some helps, but no luck for me.

Is that trying to say that I should use the 2.0.0 version of oci8 dll? The thing is there is no 2.0.0 version for Windows. >> https://pecl.php.net/package/oci8

I read so many tips on some sites, but none of it works.
There is 1 thread about it here > https://github.com/yajra/laravel-oci8/issues/353
But someone locked it even thou the issue has not been solved. And the one in the comment who maybe tried to help is not helping at all.

### Code snippet of problem

composer require yajra/laravel-oci8

### System details

- Operating System : Win 8 x64
- PHP Version: 7.2.4
- Laravel Version: 5.6
- Laravel-OCI8 Version: 2.1.8
- XAMPP x86

**Comment by shahalam-ndc** [comment]
same problem here.. How to solve ??

**Comment by goseesomething** [comment]
extract and copy all the dll files to /xampp/apache/bin/ and copy it to /xampp/php/ 

this is the last step...

It has been almost a week to find out the last step!

**Comment by FEDYCHUNG** [comment]
Hello, Every One. My name's FEDY.
Why I still get this error when run `composer require laravel/yajra-oci8` ? 

System details
- Operating System : Win 7 x32
- PHP Version: 7.3.0
- Lumen Version: 6.2.0
- Laravel-OCI8 Version: 2.2.0
- XAMPP x86

I already extract "php_oci8-2.2.0-7.3-ts-vc15-x86.zip" in:
`C:\xampp\php\ext`

Remove comment in php.ini:
`extension=php_oci8`
`extension=pdo_oci`

My phpinfo view is:

OCI8 Support | enabled
-- | --
OCI8 DTrace Support | disabled
OCI8 Version | 2.2.0
Oracle Run-time Client Library Version | 10.2.0.5.0
Oracle Compile-time Instant Client Version | 10.2

Download instantclient_10_2 and extract all dll to:
`C:\xampp\apache\bin\ `
`C:\xampp\php`
`C:\Windows\System32\drivers`

Paste all folder instantclient_10_2 in:
`C:\`

Add Enviroment Variables:
`Variable name : PATH`
`Variable value: C:\instantclient_10_2`

Where I miss ?

**Comment by nhoctanker** [comment]
> Hi, this procedure worked for me.
> After doing this you should be able to composer install yajra/laravel-oci8
> Thanks,
> 
> https://gist.github.com/jeanne007/ffe6db1b6d539544d634006d25aa32c3

Thank you it work 



**How to install OCI8 in windows**
Instantclient Version 12.2.0.1.0
Xampp
php 7.2.4
Windows 10
Step 1
Download OCI8 2.1.8 - 7.2 Thread Safe (TS) x86

Step 2
Extract the file to xampp\ext

Step 3
Add code to file xampp\php.ini

extension=php_oci8.dll
Step 4
Download the "Instant Client Package - Basic" for Windows from the OTN Instant Client page. http://www.oracle.com/technetwork/topics/winsoft-085727.html

Because PHP is 32 bit, use the 32 bit version of Instant Client. (http://www.oracle.com/technetwork/articles/technote-php-instant-084410.html)

Instant Client Package - Basic Version 12.2.0.1.0
Step 5
Extract the Instant Client folder to C:\instantclient_12_2

Step 6
Edit the Windows PATH environment setting and add this path

C:\instantclient_12_2
Step 7

**Comment by eteisman** [comment]
I cannot get this to run.

I have a working OCI connection, which I can use on successfully from PHP.
Yes installing  yajra will always give me this error. I am using version 2.2.0 of the OCI8 dll

**Comment by mstaack** [comment]
@eteisman yeah 99% of the time its a php/extensions misconfiguration ;)

**Comment by Raynaldi262** [comment]
mantap
