### ISSUE TITLE
Error ORA-28547

### ISSUE THREAD

**Issue by jonathanfreites** [yajra/laravel-oci8#53]
Hi,

I have a wep app hosted in MediaTemple but using a remote oracle database connection. In development process I was connecting ok, with a remote testing database, but now I am trying to switch to production database I cannot connect, the issue is: Error ORA-28547

Any idea??

**Comment by yajra** [comment]
I haven't encountered this issue yet but googling the error code, it maybe due to the instantclient installed on MediaTemplate. Check if your dev and prod server does have the same version. Also you might want check this link [ORA-28547](https://community.oracle.com/thread/2263004):

**As the link suggested**
You are using instant client lite version... this version only supports characterset:
Single-byte character sets include US7ASCII, WE8DEC, WE8MSWIN1252, and WE8ISO8859P1.
Unicode character sets include UTF8, AL16UTF16, and AL32UTF8.

Most likely your characterset is non of the above.
Can check using this command:
SELECT * FROM nls_database_parameters WHERE parameter = 'NLS_CHARACTERSET';

Can read more about this from here...
http://download.oracle.com/docs/cd/B28359_01/server.111/b31189/apd.htm

**Comment by jonathanfreites** [comment]
Thank you so much! I'll try this!
