### ISSUE TITLE
php artisan migrate

### ISSUE THREAD

**Issue by TwinLight** [yajra/laravel-oci8#92]
I already run "php artisan migrate:install", and then i run "php artisan migrate". But it came out this error message:
![capture](https://cloud.githubusercontent.com/assets/9023187/10410792/df726744-6f7e-11e5-8f15-398dcb00fce7.PNG)

Here my User model:
![asd](https://cloud.githubusercontent.com/assets/9023187/10410811/5580a7e8-6f7f-11e5-9098-d5f1209fa364.PNG)

My question is:
-It is because oracle syntax is different than mysql syntax?
-And does this package support autoincrement features?

I'm using Oracle 11g R2 Express.

**Comment by yajra** [comment]
**It is because oracle syntax is different than mysql syntax?**
I think the problem on your query is that Staff table does not exists yet. But I do agree that some SQLs may work on MySQL but not on Oracle because of the way Oracle handles things. Like the dates, null values, etc.

**And does this package support autoincrement features?**
Yes, the package supports autoincrement provided you use the migration for creating tables.

**Comment by TwinLight** [comment]
Thank you, just relies that i need to comment first any field related to foreign key. Thank you for awesome packagist

**Comment by angelobioko** [comment]
when i run php artisan migrate for all my migrations i get the error "CALL TO UNDEFINED FUNCTION YAJRA\PDO\OCI_CONNECT". what do i have to do to make it work.

I use oracle 11g database.
