### ISSUE TITLE
About oracle default Date format

### ISSUE THREAD

**Issue by TwinLight** [yajra/laravel-oci8#96]
Hello again, https://github.com/yajra/laravel-oci8/wiki/Date-Formatting, i have difficulty in this part, where should i put this code actually. Is it in my model class or controller? I do want to my make date with this format "MM/DD/YYYY"

One more thing is that, i have declare this variable(model class),  but it seems the dates attribute doesn't make as Carbon istance: 
protected $dates = ['tarikh_beli', 'tarikh_lupus'];

**Comment by yajra** [comment]
What version of Laravel are you using? Setting the dates property should make those fields as carbon instance as long as it is a valid date. It's a default Laravel feature and is not part of the package.

```php
protected $dates = ['tarikh_beli', 'tarikh_lupus'];
```

On the other hand, setting the Oracle session date format to another is not really advisable as it may cause some issues since oracle is very sensitive in handling dates. I personally use the default format `YYYY-MM-DD HH:MI:SS` and just use the carbon instance to present the data to new format.

**Comment by TwinLight** [comment]
its laravel/framework": "5.1.*, 
Im not sure whenever i type in dd('tarikh_beli'), it just dont give me a Carbon instance. 
Okay i will keep the format as it is YYYY-MM-DD HH:MI:SS.

**Comment by c0debreak** [comment]
I get the error message "ORA-01 861: literal does not match format string" when insert date format,

This is my controller code:

$ data = ['FLD01' => $ request-> input ('code'), 'FLD02' => date ('Ym-d')];
DB :: setDateFormat ('DD-MON-YYYY');
Application :: create ($ data);

anyone can help?

**Comment by TwinLight** [comment]
i'm not so sure about that date format, but in sql i use 
``` 
TO_DATE('03/05/2015', 'dd/mm/yyyy')
```
to insert date.

**Comment by yajra** [comment]
https://github.com/yajra/laravel-oci8/issues/103 Fixed.
